// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

var Root = {};

var Client = {
  Root: Root
};

var Ref = {};

var Props = {};

function useRef(param) {
  return React.useRef(null);
}

var Style;

exports.Client = Client;
exports.Ref = Ref;
exports.Props = Props;
exports.Style = Style;
exports.useRef = useRef;
/* react Not a pure module */
