// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

var Root = {};

var Client = {
  Root: Root
};

var Ref = {};

var Props = {};

var baseRef = React.useRef(null);

var Style;

var useRef = baseRef;

exports.Client = Client;
exports.Ref = Ref;
exports.Props = Props;
exports.Style = Style;
exports.useRef = useRef;
/* baseRef Not a pure module */
